import gzip
import stat
import shutil
import subprocess
import tomllib

from pathlib import Path
from rich.console import Console

from info import APP_AUTHOR, APP_GITHUB, APP_WEBSITE
from detector import detect_icon_set, is_jar_artifact

console = Console()

VALID_SERVICE_TYPES = {"simple", "oneshot", "notify", "forking"}
VALID_RESTART = {"no", "on-failure", "always", "on-abnormal"}
MAINTAINER_SCRIPT_HOOKS = ("preinst", "postinst", "prerm", "postrm")


def _sanitize_single_line(value: str) -> str:
    """Debian control / .desktop n'acceptent pas de saut de ligne brut dans
    un champ 'simple'. On aplatit en une seule ligne plutot que de risquer
    un fichier malforme (control corrompu, .desktop ignore par le menu)."""
    if not value:
        return value
    return " ".join(value.split())


def _control_description(description: str) -> str:
    """Format Debian pour Description: la 1re ligne est la description
    courte, chaque ligne suivante doit etre indentee d'au moins un espace
    (une ligne vide devient '.'). On construit ce format meme si
    `description` ne contient qu'une ligne."""
    lines = [l for l in (description or "").splitlines() if l.strip()] or [""]
    short = _sanitize_single_line(lines[0])
    extra = lines[1:]
    out = f"Description: {short}\n"
    for l in extra:
        l = l.strip()
        out += f" {l if l else '.'}\n"
    return out


def _build_unit_content(service: dict, app_name: str, description_fallback: str) -> str:
    svc_type = service.get("type") or "simple"
    if svc_type not in VALID_SERVICE_TYPES:
        svc_type = "simple"

    restart = service.get("restart") or "on-failure"
    if restart not in VALID_RESTART:
        restart = "on-failure"

    user = service.get("user") or "root"
    args = service.get("args") or ""
    exec_start = f"/usr/bin/{app_name}" + (f" {args}" if args else "")
    description = _sanitize_single_line(service.get("description") or description_fallback)

    lines = [
        "[Unit]",
        f"Description={description}",
        "After=network.target",
        "",
        "[Service]",
        f"Type={svc_type}",
        f"ExecStart={exec_start}",
        f"User={user}",
        f"Restart={restart}",
        "",
        "[Install]",
        "WantedBy=multi-user.target",
        "",
    ]
    return "\n".join(lines)


def _write_services(build_root: Path, services: list[dict], app_name: str, description_fallback: str) -> list[tuple]:
    """Ecrit les fichiers .service dans DEBIAN et renvoie la liste des noms d'unites."""
    if not services:
        return []

    systemd_dir = build_root / "usr" / "lib" / "systemd" / "system"
    systemd_dir.mkdir(parents=True, exist_ok=True)

    unit_names = []
    for service in services:
        name = service.get("name")
        if not name:
            continue
        unit_name = f"{name}.service"
        content = _build_unit_content(service, app_name, description_fallback)
        (systemd_dir / unit_name).write_text(content, encoding="utf-8")
        unit_names.append((unit_name, bool(service.get("enable", True))))

    return unit_names


def _autogenerated_script_body(hook: str, unit_names: list[tuple]) -> str:
    """Corps (sans shebang/set -e/exit 0) de la partie systemd auto-generee
    pour un hook donne. Vide si aucun service n'est defini."""
    if not unit_names:
        return ""

    if hook == "postinst":
        enable_lines = [
            f"    systemctl enable --now {unit_name} >/dev/null 2>&1 || true"
            for unit_name, enable in unit_names if enable
        ]
        enable_block = ("\n" + "\n".join(enable_lines)) if enable_lines else ""
        return (
            "if command -v systemctl >/dev/null 2>&1; then\n"
            "    systemctl daemon-reload >/dev/null 2>&1 || true" + enable_block + "\nfi"
        )

    if hook == "prerm":
        stop_lines = "\n".join(
            f"    systemctl stop {unit_name} >/dev/null 2>&1 || true\n"
            f"    systemctl disable {unit_name} >/dev/null 2>&1 || true"
            for unit_name, _ in unit_names
        )
        return f"if command -v systemctl >/dev/null 2>&1; then\n{stop_lines}\nfi"

    if hook == "postrm":
        return (
            "if command -v systemctl >/dev/null 2>&1; then\n"
            "    systemctl daemon-reload >/dev/null 2>&1 || true\nfi"
        )

    return ""


def _strip_shebang_and_trailer(text: str) -> str:
    lines = text.splitlines()
    if lines and lines[0].startswith("#!"):
        lines = lines[1:]
    while lines and lines[-1].strip() in ("", "exit 0"):
        lines.pop()
    return "\n".join(lines)


def _write_maintainer_scripts(project: Path, debian_dir: Path, unit_names: list[tuple], user_scripts: dict):
    """Ecrit preinst/postinst/prerm/postrm en fusionnant :
      1. la logique systemd auto-generee par meb (activation/arret des
         services definis dans meb.toml) ;
      2. un script fourni par l'utilisateur pour le meme hook (meb.toml
         [scripts]), insere a la suite, shebang/exit retires pour eviter un
         script a deux 'set -e'/'exit 0' contradictoires.
    Un hook sans contenu (ni auto, ni utilisateur) n'est pas ecrit."""
    for hook in MAINTAINER_SCRIPT_HOOKS:
        auto_body = _autogenerated_script_body(hook, unit_names)

        user_body = ""
        user_rel = user_scripts.get(hook)
        if user_rel:
            user_path = project / user_rel
            if user_path.exists():
                user_body = _strip_shebang_and_trailer(user_path.read_text(encoding="utf-8", errors="ignore"))
            else:
                console.print(f"[yellow]! Script '{hook}' introuvable, ignoré : {user_rel}[/yellow]")

        if not auto_body and not user_body:
            continue

        parts = ["#!/bin/sh", "set -e", ""]
        if auto_body:
            parts.append(auto_body)
        if user_body:
            parts.append(user_body)
        parts.append("")
        parts.append("exit 0")
        content = "\n".join(parts) + "\n"

        target = debian_dir / hook
        target.write_text(content, encoding="utf-8")
        target.chmod(target.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def _install_resources(project: Path, build_root: Path, resources: list[dict]):
    for r in resources:
        source = r.get("source")
        dest = r.get("dest")
        if not source or not dest:
            continue
        src_path = project / source
        if not src_path.exists():
            console.print(f"[yellow]! Ressource introuvable, ignorée : {source}[/yellow]")
            continue

        dest_path = build_root / dest.lstrip("/")
        if src_path.is_dir():
            shutil.copytree(src_path, dest_path, dirs_exist_ok=True)
        else:
            dest_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_path, dest_path)

        mode = r.get("mode")
        if mode:
            try:
                dest_path.chmod(int(mode, 8))
            except (ValueError, OSError):
                console.print(f"[yellow]! Mode invalide pour {source}, ignoré : {mode}[/yellow]")

    if resources:
        console.print(f"[green]✔ {len(resources)} ressource(s) additionnelle(s) embarquee(s)[/green]")


def _install_man_pages(project: Path, build_root: Path, man_pages: list[dict]):
    for m in man_pages:
        source = m.get("source")
        section = m.get("section", 1)
        if not source:
            continue
        src_path = project / source
        if not src_path.exists():
            console.print(f"[yellow]! Page de manuel introuvable, ignorée : {source}[/yellow]")
            continue

        man_dir = build_root / "usr" / "share" / "man" / f"man{section}"
        man_dir.mkdir(parents=True, exist_ok=True)
        target_name = Path(source).stem if Path(source).suffix == f".{section}" else Path(source).name
        gz_path = man_dir / f"{target_name}.{section}.gz"

        raw = src_path.read_bytes()
        # mtime=0 : paquet reproductible (deux builds identiques produisent
        # le meme .gz octet pour octet).
        with open(gz_path, "wb") as fh:
            with gzip.GzipFile(filename="", mode="wb", fileobj=fh, mtime=0) as gz:
                gz.write(raw)

    if man_pages:
        console.print(f"[green]✔ {len(man_pages)} page(s) de manuel installée(s)[/green]")


def _install_completions(project: Path, build_root: Path, completions: dict, name: str):
    targets = {
        "bash": build_root / "usr" / "share" / "bash-completion" / "completions" / name,
        "zsh": build_root / "usr" / "share" / "zsh" / "site-functions" / f"_{name}",
        "fish": build_root / "usr" / "share" / "fish" / "vendor_completions.d" / f"{name}.fish",
    }
    auto_stubs = {
        "bash": (
            f'_{name}_completions() {{\n'
            f'    COMPREPLY=($(compgen -W "$({name} --help 2>/dev/null | grep -oE \'^  [a-z-]+\')" -- "${{COMP_WORDS[COMP_CWORD]}}"))\n'
            f'}}\n'
            f'complete -F _{name}_completions {name}\n'
        ),
        "zsh": f"#compdef {name}\n_arguments '*:: :->args'\n_describe 'command' \"($( {name} --help 2>/dev/null | grep -oE '^  [a-z-]+' ))\"\n",
        "fish": f"complete -c {name} -f\n",
    }

    installed = 0
    for shell, value in completions.items():
        target = targets.get(shell)
        if not target or not value:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)

        if value == "auto":
            target.write_text(auto_stubs[shell], encoding="utf-8")
            installed += 1
            continue

        src_path = project / value
        if not src_path.exists():
            console.print(f"[yellow]! Complétion {shell} introuvable, ignorée : {value}[/yellow]")
            continue
        shutil.copy2(src_path, target)
        installed += 1

    if installed:
        console.print(f"[green]✔ Auto-completion installée pour {installed} shell(s)[/green]")


def _install_conffiles(project: Path, build_root: Path, conffiles: list[dict]) -> list[str]:
    dests = []
    for c in conffiles:
        source = c.get("source")
        dest = c.get("dest")
        if not source or not dest:
            continue
        src_path = project / source
        if not src_path.exists():
            console.print(f"[yellow]! Fichier de config introuvable, ignoré : {source}[/yellow]")
            continue
        dest_path = build_root / dest.lstrip("/")
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_path, dest_path)
        dests.append(dest)

    if dests:
        (build_root / "DEBIAN" / "conffiles").write_text("\n".join(dests) + "\n", encoding="utf-8")
        console.print(f"[green]✔ {len(dests)} fichier(s) de configuration marqué(s) conffiles[/green]")
    return dests


def _apply_permissions(build_root: Path, permissions: list[dict]):
    for p in permissions:
        rel = p.get("path", "").lstrip("/")
        mode = p.get("mode")
        if not rel or not mode:
            continue
        target = build_root / rel
        if not target.exists():
            console.print(f"[yellow]! Permission ignorée, chemin introuvable dans le paquet : {rel}[/yellow]")
            continue
        try:
            target.chmod(int(mode, 8))
        except (ValueError, OSError):
            console.print(f"[yellow]! Mode invalide pour {rel}, ignoré : {mode}[/yellow]")


def _install_icons(icons_base: Path, icon_path: Path, name: str) -> str | None:
    """Installe une icone (fichier unique ou dossier) dans hicolor/, en
    placant chaque resolution detectee dans le bon sous-dossier <n>x<n>/apps
    (ou scalable/apps pour un SVG) au lieu de toujours forcer 256x256."""
    icon_set = detect_icon_set(icon_path)
    if not icon_set:
        return None

    for size, src in icon_set.items():
        size_dir = icons_base / size / "apps"
        size_dir.mkdir(parents=True, exist_ok=True)
        dest = size_dir / f"{name}{src.suffix}"
        shutil.copy2(src, dest)

    return name


def run(path: str = ".", output: str = "dist"):
    project = Path(path).resolve()
    config_file = project / "meb.toml"

    if not config_file.exists():
        console.print("[red]✘ meb.toml introuvable. Lance 'meb init' d'abord.[/red]")
        raise SystemExit(1)

    with open(config_file, "rb") as f:
        config = tomllib.load(f)

    name = config.get("name")
    version = config.get("version", "1.0.0")
    description = config.get("description", "")
    language = config.get("language", "")
    package_cfg = config.get("package", {})
    arch = package_cfg.get("architecture", "amd64")
    section = package_cfg.get("section") or "utils"
    priority = package_cfg.get("priority") or "optional"
    depends = list(package_cfg.get("depends", []))
    app = config.get("app", {})
    exec_rel = app.get("exec")
    icon_rel = app.get("icon")
    maintainer = config.get("maintainer") or "unknown <unknown@example.com>"
    category = app.get("category", "Utility")
    make_desktop = app.get("desktop", True)
    terminal = app.get("terminal", True)
    startup_wm_class = app.get("startup_wm_class", "")
    readme_rel = app.get("readme", "")
    services = config.get("services", [])
    resources = config.get("resources", [])
    man_pages = config.get("man", [])
    completions = config.get("completions", {})
    conffiles = config.get("conffiles", [])
    user_scripts = config.get("scripts", {})
    permissions = config.get("permissions", [])

    if not name or not exec_rel:
        console.print("[red]✘ Configuration incomplète (name / app.exec requis). Lance 'meb check'.[/red]")
        raise SystemExit(1)

    exec_path = project / exec_rel
    if not exec_path.exists():
        console.print(f"[red]✘ Exécutable introuvable : {exec_rel}[/red]")
        raise SystemExit(1)

    pkg_dirname = f"{name}_{version}_{arch}"
    out_dir = project / output
    build_root = out_dir / pkg_dirname

    console.print(f"[cyan]Construction du paquet : {pkg_dirname}.deb[/cyan]")

    if build_root.exists():
        shutil.rmtree(build_root)

    debian_dir = build_root / "DEBIAN"
    bin_dir = build_root / "usr" / "bin"
    apps_dir = build_root / "usr" / "share" / "applications"
    icons_base = build_root / "usr" / "share" / "icons" / "hicolor"
    doc_dir = build_root / "usr" / "share" / "doc" / name

    debian_dir.mkdir(parents=True)
    bin_dir.mkdir(parents=True)

    # Executable (ou lanceur, pour Java qui n'a pas de binaire natif)
    if is_jar_artifact(exec_path):
        jar_dir = build_root / "usr" / "share" / name
        jar_dir.mkdir(parents=True, exist_ok=True)
        jar_dest = jar_dir / f"{name}.jar"
        shutil.copy2(exec_path, jar_dest)

        dest_exec = bin_dir / name
        dest_exec.write_text(
            f'#!/bin/sh\nexec java -jar "/usr/share/{name}/{name}.jar" "$@"\n',
            encoding="utf-8",
        )
        if language == "java" and not any("jre" in d.lower() or "jdk" in d.lower() for d in depends):
            depends.append("default-jre-headless | java17-runtime-headless | java-runtime-headless")
        console.print(f"[green]✔ Lanceur Java généré pour {jar_dest.name}[/green]")
    else:
        dest_exec = bin_dir / name
        shutil.copy2(exec_path, dest_exec)

    dest_exec.chmod(dest_exec.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    # Icone(s) - multi-resolution
    icon_installed_name = None
    if icon_rel:
        icon_path = project / icon_rel
        if icon_path.exists():
            icon_installed_name = _install_icons(icons_base, icon_path, name)
        else:
            console.print(f"[yellow]! Icône introuvable, ignorée : {icon_rel}[/yellow]")

    # Fichier .desktop (lanceur d'application) - optionnel
    if make_desktop:
        apps_dir.mkdir(parents=True, exist_ok=True)
        desktop_file = apps_dir / f"{name}.desktop"
        desktop_lines = [
            "[Desktop Entry]",
            "Type=Application",
            f"Name={_sanitize_single_line(name)}",
            f"Comment={_sanitize_single_line(description)}",
            f"Exec={name}",
            f"Icon={icon_installed_name or name}",
            f"Terminal={'true' if terminal else 'false'}",
            f"Categories={_sanitize_single_line(category)};",
        ]
        if startup_wm_class:
            desktop_lines.append(f"StartupWMClass={_sanitize_single_line(startup_wm_class)}")
        desktop_file.write_text("\n".join(desktop_lines) + "\n", encoding="utf-8")

    # README embarque
    if readme_rel:
        readme_path = project / readme_rel
        if readme_path.exists():
            doc_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(readme_path, doc_dir / readme_path.name)
        else:
            console.print(f"[yellow]! README introuvable, ignoré : {readme_rel}[/yellow]")

    # Ressources additionnelles (themes, plugins .so, polices, sons, traductions, modeles...)
    _install_resources(project, build_root, resources)

    # Pages de manuel
    _install_man_pages(project, build_root, man_pages)

    # Auto-completion shell
    _install_completions(project, build_root, completions, name)

    # Fichiers de configuration (conffiles)
    _install_conffiles(project, build_root, conffiles)

    # Services systemd (optionnels) + scripts de maintainer (auto + custom)
    unit_names = _write_services(build_root, services, name, description)
    if unit_names:
        console.print(f"[green]✔ {len(unit_names)} service(s) systemd empaqueté(s)[/green]")
        depends_has_systemd = any(d.strip().lower().startswith("systemd") for d in depends)
        if not depends_has_systemd:
            depends.append("systemd")
    _write_maintainer_scripts(project, debian_dir, unit_names, user_scripts)

    # Permissions personnalisees (apres toutes les copies, avant le packaging)
    _apply_permissions(build_root, permissions)

    # DEBIAN/control
    installed_size_kb = max(1, sum(f.stat().st_size for f in build_root.rglob("*") if f.is_file()) // 1024)
    control_content = (
        f"Package: {name}\n"
        f"Version: {version}\n"
        f"Section: {section}\n"
        f"Priority: {priority}\n"
        f"Architecture: {arch}\n"
        f"Maintainer: {maintainer}\n"
        f"Installed-Size: {installed_size_kb}\n"
        f"Homepage: {APP_GITHUB}\n"
    )
    if depends:
        control_content += f"Depends: {', '.join(dict.fromkeys(depends))}\n"
    control_content += _control_description(description)
    (debian_dir / "control").write_text(control_content, encoding="utf-8")

    # dpkg-deb
    deb_path = out_dir / f"{pkg_dirname}.deb"
    try:
        subprocess.run(
            ["dpkg-deb", "--build", "--root-owner-group", str(build_root), str(deb_path)],
            check=True,
        )
    except FileNotFoundError:
        console.print("[red]✘ dpkg-deb introuvable. Installe le paquet 'dpkg'.[/red]")
        raise SystemExit(1)
    except subprocess.CalledProcessError as e:
        console.print(f"[red]✘ Échec de dpkg-deb : {e}[/red]")
        raise SystemExit(1)

    console.print(f"[green]✔ Paquet créé : {deb_path}[/green]")
    console.print(f"[dim]Meb — par {APP_AUTHOR} · {APP_GITHUB} · {APP_WEBSITE}[/dim]")


if __name__ == "__main__":
    run()
